"""Добавлен столбец к topics для описания темы

Revision ID: 27d0e29d11d4
Revises: e11a6b0f236a
Create Date: 2021-04-03 18:21:44.057823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27d0e29d11d4'
down_revision = 'e11a6b0f236a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topics', sa.Column('text', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topics', 'text')
    # ### end Alembic commands ###
