"""Добавлена модель категории тем

Revision ID: 27fe5a63d7bc
Revises: 27d0e29d11d4
Create Date: 2021-04-15 17:49:59.509359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27fe5a63d7bc'
down_revision = '27d0e29d11d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.add_column('topics', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'topics', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'topics', type_='foreignkey')
    op.drop_column('topics', 'category_id')
    op.drop_table('categories')
    # ### end Alembic commands ###
