"""Добавлен параметр is_locked для Topic и Category

Revision ID: cd1342431b77
Revises: f026839ce8a3
Create Date: 2021-04-20 19:23:55.243537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd1342431b77'
down_revision = 'f026839ce8a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_locked', sa.Boolean(), nullable=True, server_default="0"))

    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_locked', sa.Boolean(), nullable=True, server_default="0"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.drop_column('is_locked')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_column('is_locked')

    # ### end Alembic commands ###
