"""Разделение пользователей на администраторов и на обычных пользователей

Revision ID: f026839ce8a3
Revises: e0f9fae574cc
Create Date: 2021-04-20 13:24:16.419601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f026839ce8a3'
down_revision = 'e0f9fae574cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.Enum('admin', 'user', name='role'), nullable=True, server_default="user"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
